<a href="https://colab.research.google.com/github/chinmayhandi/chinmay/blob/chinmay/autocar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv('/content/auto_mpg_sample.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,27.6,3,94.4,181.8,4989,16.5,78,japan,car_model_1
1,28.2,3,380.8,NaN,2608,18.6,76,europe,car_model_2
2,33.4,3,303.3,171.7,2939,14.7,70,usa,car_model_3
3,36.3,8,294.1,183.7,3563,12.5,71,europe,car_model_4
4,34.1,5,287.1,225.6,1712,17.0,71,usa,car_model_5
5,11.3,4,77.5,NaN,3239,10.3,73,europe,car_model_6
6,27.4,5,311.5,122.1,4358,10.4,70,japan,car_model_7
7,15.1,8,254.7,199.0,3558,14.9,82,japan,car_model_8
8,30.4,8,148.2,NaN,2505,13.6,81,japan,car_model_9
9,14.8,5,149.0,87.1,2499,10.8,73,japan,car_model_10
10,32.6,5,115.1,220.0,2102,16.7,74,usa,car_model_11
11,35.4,5,376.4,78.0,4642,11.4,70,usa,car_model_12
12,36.6,4,191.3,163.1,3797,19.0,75,europe,car_model_13
13,34.6,8,384.0,112.3,2641,16.5,75,europe,car_model_14
14,22.5,4,337.7,143.8,4273,12.5,70,europe,car_model_15
15,16.5,4,270.0,80.3,3414,14.4,71,japan,car_model_16
16,31.6,4,225.3,NaN,3190,12.9,80,europe,car_model_17
17,21.2,4,277.7,59.5,4088,16.5,74,usa,car_model_18
18,23.4,8,410.9,NaN,4189,13.2,74,japan,car_model_19
19,22.3,6,265.7,146.7,3327,18.5,82,europe,car_model_20
20,15.7,8,415.6,146.7,4430,16.7,77,europe,car_model_21
21,38.3,3,126.6,146.7,2523,18.9,77,usa,car_model_22
22,13.7,3,136.1,146.7,4188,14.9,72,europe,car_model_23
23,36.9,6,213.0,146.7,3634,16.5,80,usa,car_model_24
24,19.8,6,194.3,146.7,2225,19.9,70,europe,car_model_25
25,14.5,4,94.1,146.7,4781,11.3,77,usa,car_model_26
26,18.5,6,209.2,NaN,1690,10.7,81,europe,car_model_27
27,11.6,3,214.4,146.7,4417,11.7,77,europe,car_model_28
28,18.9,5,204.2,146.7,1835,12.8,71,europe,car_model_29
29,30.5,3,118.1,146.7,2025,14.6,82,usa,car_model_30
30,33.9,4,272.5,146.7,4012,12.6,75,usa,car_model_31
31,15.3,3,255.2,146.7,3634,18.4,71,europe,car_model_32
32,20.5,3,370.0,146.7,4485,9.4,81,japan,car_model_33
33,14.4,4,174.6,146.7,2603,13.0,74,japan,car_model_34
34,20.9,5,364.4,146.7,3845,15.9,74,europe,car_model_35
35,11.1,5,254.8,146.7,3228,8.5,74,usa,car_model_36
36,11.0,3,322.7,146.7,3218,12.6,71,japan,car_model_37
37,13.2,5,257.9,146.7,2173,11.4,81,usa,car_model_38
38,35.3,8,405.1,146.7,3975,14.8,82,japan,car_model_39
39,23.6,8,249.4,146.7,4671,19.4,79,usa,car_model_40
40,33.1,8,389.3,146.7,4071,19.5,82,europe,car_model_41
41,22.7,3,148.8,146.7,2305,10.6,75,japan,car_model_42
42,36.6,3,218.3,146.7,1662,19.8,78,usa,car_model_43
43,23.4,6,96.8,146.7,3151,17.3,82,japan,car_model_44
44,12.3,4,165.1,146.7,2449,16.9,73,usa,car_model_45
45,38.6,3,99.0,146.7,3076,8.4,76,usa,car_model_46
46,31.8,3,72.9,146.7,4879,14.0,78,europe,car_model_47
47,23.6,8,219.6,146.7,4079,19.2,72,usa,car_model_48
48,33.5,3,219.2,146.7,2171,9.7,75,japan,car_model_49
49,15.8,3,436.4,146.7,2719,15.1,77,japan,car_model_50

In [31]:
# Drop 'name' column safely
df.drop('name', axis=1, inplace=True, errors='ignore')

print("\nDataset after dropping 'name' column:")
print(df.head())

Dataset after dropping 'name' column:
    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  27.6          3          94.4       181.8    4989          16.5
1  28.2          3         380.8         NaN    2608          18.6
2  33.4          3         303.3       171.7    2939          14.7
3  36.3          8         294.1       183.7    3563          12.5
4  34.1          5         287.1       225.6    1712          17.0

   model_year  origin
0          78   japan
1          76  europe
2          70     usa
3          71  europe
4          71     usa

In [32]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['origin']=le.fit_transform(df['origin'])
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,27.6,3,94.4,181.8,4989,16.5,78,1
1,28.2,3,380.8,NaN,2608,18.6,76,0
2,33.4,3,303.3,171.7,2939,14.7,70,2
3,36.3,8,294.1,183.7,3563,12.5,71,0
4,34.1,5,287.1,225.6,1712,17.0,71,2
5,11.3,4,77.5,NaN,3239,10.3,73,0
6,27.4,5,311.5,122.1,4358,10.4,70,1
7,15.1,8,254.7,199.0,3558,14.9,82,1
8,30.4,8,148.2,NaN,2505,13.6,81,1
9,14.8,5,149.0,87.1,2499,10.8,73,1
10,32.6,5,115.1,220.0,2102,16.7,74,2
11,35.4,5,376.4,78.0,4642,11.4,70,2
12,36.6,4,191.3,163.1,3797,19.0,75,0
13,34.6,8,384.0,112.3,2641,16.5,75,0
14,22.5,4,337.7,143.8,4273,12.5,70,0
15,16.5,4,270.0,80.3,3414,14.4,71,1
16,31.6,4,225.3,NaN,3190,12.9,80,0
17,21.2,4,277.7,59.5,4088,16.5,74,2
18,23.4,8,410.9,NaN,4189,13.2,74,1
19,22.3,6,265.7,146.7,3327,18.5,82,0
20,15.7,8,415.6,146.7,4430,16.7,77,0
21,38.3,3,126.6,146.7,2523,18.9,77,2
22,13.7,3,136.1,146.7,4188,14.9,72,0
23,36.9,6,213.0,146.7,3634,16.5,80,2
24,19.8,6,194.3,146.7,2225,19.9,70,0
25,14.5,4,94.1,146.7,4781,11.3,77,2
26,18.5,6,209.2,NaN,1690,10.7,81,0
27,11.6,3,214.4,146.7,4417,11.7,77,0
28,18.9,5,204.2,146.7,1835,12.8,71,0
29,30.5,3,118.1,146.7,2025,14.6,82,2
30,33.9,4,272.5,146.7,4012,12.6,75,2
31,15.3,3,255.2,146.7,3634,18.4,71,0
32,20.5,3,370.0,146.7,4485,9.4,81,1
33,14.4,4,174.6,146.7,2603,13.0,74,1
34,20.9,5,364.4,146.7,3845,15.9,74,0
35,11.1,5,254.8,146.7,3228,8.5,74,2
36,11.0,3,322.7,146.7,3218,12.6,71,1
37,13.2,5,257.9,146.7,2173,11.4,81,2
38,35.3,8,405.1,146.7,3975,14.8,82,1
39,23.6,8,249.4,146.7,4671,19.4,79,2
40,33.1,8,389.3,146.7,4071,19.5,82,0
41,22.7,3,148.8,146.7,2305,10.6,75,1
42,36.6,3,218.3,146.7,1662,19.8,78,2
43,23.4,6,96.8,146.7,3151,17.3,82,1
44,12.3,4,165.1,146.7,2449,16.9,73,2
45,38.6,3,99.0,146.7,3076,8.4,76,2
46,31.8,3,72.9,146.7,4879,14.0,78,0
47,23.6,8,219.6,146.7,4079,19.2,72,2
48,33.5,3,219.2,146.7,2171,9.7,75,1
49,15.8,3,436.4,146.7,2719,15.1,77,1

In [33]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [38]:
df.fillna(df.mean(),inplace=True)
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [40]:
x=df.iloc[:, 1:8]
y=df[['mpg']]
x

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,3,94.4,181.800000,4989,16.5,78,1
1,3,380.8,146.113636,2608,18.6,76,0
2,3,303.3,171.700000,2939,14.7,70,2
3,8,294.1,183.700000,3563,12.5,71,0
4,5,287.1,225.600000,1712,17.0,71,2
5,4,77.5,146.113636,3239,10.3,73,0
6,5,311.5,122.100000,4358,10.4,70,1
7,8,254.7,199.000000,3558,14.9,82,1
8,8,148.2,146.113636,2505,13.6,81,1
9,5,149.0,87.100000,2499,10.8,73,1
10,5,115.1,220.000000,2102,16.7,74,2
11,5,376.4,78.000000,4642,11.4,70,2
12,4,191.3,163.100000,3797,19.0,75,0
13,8,384.0,112.300000,2641,16.5,75,0
14,4,337.7,143.800000,4273,12.5,70,0
15,4,270.0,80.300000,3414,14.4,71,1
16,4,225.3,146.113636,3190,12.9,80,0
17,4,277.7,59.500000,4088,16.5,74,2
18,8,410.9,146.113636,4189,13.2,74,1
19,6,265.7,146.700000,3327,18.5,82,0
20,8,415.6,146.700000,4430,16.7,77,0
21,3,126.6,146.700000,2523,18.9,77,2
22,3,136.1,146.700000,4188,14.9,72,0
23,6,213.0,146.700000,3634,16.5,80,2
24,6,194.3,146.700000,2225,19.9,70,0
25,4,94.1,146.700000,4781,11.3,77,2
26,6,209.2,146.113636,1690,10.7,81,0
27,3,214.4,146.700000,4417,11.7,77,0
28,5,204.2,146.700000,1835,12.8,71,0
29,3,118.1,146.700000,2025,14.6,82,2
30,4,272.5,146.700000,4012,12.6,75,2
31,3,255.2,146.700000,3634,18.4,71,0
32,3,370.0,146.700000,4485,9.4,81,1
33,4,174.6,146.700000,2603,13.0,74,1
34,5,364.4,146.700000,3845,15.9,74,0
35,5,254.8,146.700000,3228,8.5,74,2
36,3,322.7,146.700000,3218,12.6,71,1
37,5,257.9,146.700000,2173,11.4,81,2
38,8,405.1,146.700000,3975,14.8,82,1
39,8,249.4,146.700000,4671,19.4,79,2
40,8,389.3,146.700000,4071,19.5,82,0
41,3,148.8,146.700000,2305,10.6,75,1
42,3,218.3,146.700000,1662,19.8,78,2
43,6,96.8,146.700000,3151,17.3,82,1
44,4,165.1,146.700000,2449,16.9,73,2
45,3,99.0,146.700000,3076,8.4,76,2
46,3,72.9,146.700000,4879,14.0,78,0
47,8,219.6,146.700000,4079,19.2,72,2
48,3,219.2,146.700000,2171,9.7,75,1
49,3,436.4,146.700000,2719,15.1,77,1

In [41]:
y

     mpg
0   27.6
1   28.2
2   33.4
3   36.3
4   34.1
5   11.3
6   27.4
7   15.1
8   30.4
9   14.8
10  32.6
11  35.4
12  36.6
13  34.6
14  22.5
15  16.5
16  31.6
17  21.2
18  23.4
19  22.3
20  15.7
21  38.3
22  13.7
23  36.9
24  19.8
25  14.5
26  18.5
27  11.6
28  18.9
29  30.5
30  33.9
31  15.3
32  20.5
33  14.4
34  20.9
35  11.1
36  11.0
37  13.2
38  35.3
39  23.6
40  33.1
41  22.7
42  36.6
43  23.4
44  12.3
45  38.6
46  31.8
47  23.6
48  33.5
49  15.8

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [43]:
x_train

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
33,4,174.6,146.700000,2603,13.0,74,1
35,5,254.8,146.700000,3228,8.5,74,2
26,6,209.2,146.113636,1690,10.7,81,0
34,5,364.4,146.700000,3845,15.9,74,0
18,8,410.9,146.113636,4189,13.2,74,1
7,8,254.7,199.000000,3558,14.9,82,1
14,4,337.7,143.800000,4273,12.5,70,0
45,3,99.0,146.700000,3076,8.4,76,2
48,3,219.2,146.700000,2171,9.7,75,1
29,3,118.1,146.700000,2025,14.6,82,2
15,4,270.0,80.300000,3414,14.4,71,1
30,4,272.5,146.700000,4012,12.6,75,2
32,3,370.0,146.700000,4485,9.4,81,1
16,4,225.3,146.113636,3190,12.9,80,0
42,3,218.3,146.700000,1662,19.8,78,2
20,8,415.6,146.700000,4430,16.7,77,0
43,6,96.8,146.700000,3151,17.3,82,1
8,8,148.2,146.113636,2505,13.6,81,1
13,8,384.0,112.300000,2641,16.5,75,0
25,4,94.1,146.700000,4781,11.3,77,2
5,4,77.5,146.113636,3239,10.3,73,0
17,4,277.7,59.500000,4088,16.5,74,2
40,8,389.3,146.700000,4071,19.5,82,0
49,3,436.4,146.700000,2719,15.1,77,1
1,3,380.8,146.113636,2608,18.6,76,0
12,4,191.3,163.100000,3797,19.0,75,0
37,5,257.9,146.700000,2173,11.4,81,2
24,6,194.3,146.700000,2225,19.9,70,0
6,5,311.5,122.100000,4358,10.4,70,1
23,6,213.0,146.700000,3634,16.5,80,2
36,3,322.7,146.700000,3218,12.6,71,1
21,3,126.6,146.700000,2523,18.9,77,2
19,6,265.7,146.700000,3327,18.5,82,0
9,5,149.0,87.100000,2499,10.8,73,1
39,8,249.4,146.700000,4671,19.4,79,2
46,3,72.9,146.700000,4879,14.0,78,0
3,8,294.1,183.700000,3563,12.5,71,0
0,3,94.4,181.800000,4989,16.5,78,1
47,8,219.6,146.700000,4079,19.2,72,2
44,4,165.1,146.700000,2449,16.9,73,2

In [44]:
x_test

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
28,5,204.2,146.7,1835,12.8,71,0
11,5,376.4,78.0,4642,11.4,70,2
10,5,115.1,220.0,2102,16.7,74,2
41,3,148.8,146.7,2305,10.6,75,1
2,3,303.3,171.7,2939,14.7,70,2
27,3,214.4,146.7,4417,11.7,77,0
38,8,405.1,146.7,3975,14.8,82,1
31,3,255.2,146.7,3634,18.4,71,0
22,3,136.1,146.7,4188,14.9,72,0
4,5,287.1,225.6,1712,17.0,71,2

In [45]:
y_train

     mpg
33  14.4
35  11.1
26  18.5
34  20.9
18  23.4
7   15.1
14  22.5
45  38.6
48  33.5
29  30.5
15  16.5
30  33.9
32  20.5
16  31.6
42  36.6
20  15.7
43  23.4
8   30.4
13  34.6
25  14.5
5   11.3
17  21.2
40  33.1
49  15.8
1   28.2
12  36.6
37  13.2
24  19.8
6   27.4
23  36.9
36  11.0
21  38.3
19  22.3
9   14.8
39  23.6
46  31.8
3   36.3
0   27.6
47  23.6
44  12.3

In [46]:
y_test

     mpg
28  18.9
11  35.4
10  32.6
41  22.7
2   33.4
27  11.6
38  35.3
31  15.3
22  13.7
4   34.1

In [50]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("y_pred:\n",y_pred)

y_pred:
 [[22.03979263]
 [17.15650215]
 [27.84926826]
 [22.7258732 ]
 [23.48571339]
 [24.39114589]
 [23.77507699]
 [26.66083367]
 [25.61960268]
 [26.03944347]]

In [51]:
import numpy as np
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
rmse=np.sqrt(mse)

print("Mean Squared Error:",mse)
print("Mean Absolute Error:",mae)
print("Root Mean Squared Error:",rmse)
print("R2 Score:",r2)

Mean Squared Error: 109.61020170043926
Mean Absolute Error: 9.173124381620976
Root Mean Squared Error: 10.469489084976367
R2 Score: -0.26232496891053136